# Generated by Django 5.2.7 on 2025-10-04 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERPNextCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(db_index=True, verbose_name="Organization ID"),
                ),
                (
                    "erpnext_url",
                    models.URLField(
                        help_text="The base URL of the ERPNext instance (e.g., https://mycompany.erpnext.com)",
                        verbose_name="ERPNext Site URL",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "api_secret",
                    models.CharField(max_length=255, verbose_name="API Secret"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active credentials will be used for API calls.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ERPNext Credential",
                "verbose_name_plural": "ERPNext Credentials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "is_active"],
                        name="idx_erpnext_org_active",
                    )
                ],
            },
        ),
    ]
