# Generated by Django 5.2.7 on 2025-10-02 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlegraCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=255)),
                ("token", models.TextField()),
                ("base_url", models.URLField(default="https://api.alegra.com/api/v1")),
                ("webhook_secret", models.TextField(blank=True, null=True)),
                (
                    "number_template_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("auto_stamp_on_create", models.BooleanField(default=True)),
                ("timeout_s", models.PositiveIntegerField(default=30)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("e_provider_api_key", models.TextField(blank=True, null=True)),
                ("e_provider_base_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("organization_id", "name"),
                "indexes": [
                    models.Index(
                        fields=["organization_id", "is_active"],
                        name="idx_alegra_company_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "name"),
                        name="uniq_alegra_credential_name",
                    )
                ],
            },
        ),
    ]
