# Generated by Django 5.2.7 on 2025-10-06 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopifyStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(db_index=True, verbose_name="Organization ID"),
                ),
                (
                    "shopify_domain",
                    models.CharField(
                        help_text="The .myshopify.com domain of the store.",
                        max_length=255,
                        unique=True,
                        verbose_name="Shopify Domain",
                    ),
                ),
                (
                    "webhook_shared_secret",
                    models.TextField(
                        help_text="The shared secret for validating webhooks from Shopify.",
                        verbose_name="Webhook Shared Secret",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shopify Store",
                "verbose_name_plural": "Shopify Stores",
                "ordering": ["-created_at"],
            },
        ),
    ]
